var string = {
    'en': {
        'title': "Barbershop Deluxe App Verification",
        'numberDefault': "617-219-9117",
        'enterPhone': "Please enter your mobile number, including area code.",
        'enterPhoneExtra': "617 555 1212",
        'buttonSubmit': "Continue",
        'buttonVerify': "Verify",
        'warningPhone': "You must enter a 10-digit Canadian or U.S. phone number that can receive text messages",
        'warningTwilio': "Something went wrong. Please check your Twilio configuration.",
        'warningGeneral': "Something went wrong. Please try again.",
        'warningNoNumber': "You forgot to enter your mobile number.",
        'warningCodeLength': "You must enter a 4 digit code texted to your phone number.",
        'warningCodeInvalid': "That verification code is not valid.",
        'messageWelcomeDashboard': "Welcome to your Dashboard",
        'enterCode': "Enter the 4-digit confirmation code",
        'enterCodeExtra': "It was sent in an SMS message to",
        'emailLogin': "Your login code for the Barbershop Deluxe app is",
        'dashboardWelcome': "Welcome to your Dashboard",
        'dashboardNumber': "Your Number",
        'dashboardName': "Your Name",
        'dashboardNameHint': "Nick Fury",
        'dashboardSetting1': "Orbital Tracking Grid",
        'dashboardSetting2': "Iron Legion",
        'dashboardSetting3': "Theta Protocol",
        'dashboardUpdate': "Update",
        'dashboardFinished': "Are you finished?",
        'dashboardLogout': "Logout",
        'alertOK': "OK",
    },
    'es': {
        'title': "AnyPhone",
        'numberDefault': "090-1234-5678",
        'enterPhone': "Introduce tu número",
        'enterPhoneExtra': "Este ejemplo está limitado a un número de 10-digitos (US)",
        'buttonSubmit': "Continuar",
        'buttonVerify': "Verificar",
        'warningPhone': "Debes introducir un número de 10 dígitos incluyendo su código de área (US)",
        'warningTwilio': "Algo salió mal. Por favor verifica tú configuración de Twilio.",
        'warningGeneral': "Algo salió mal. Por favor intenta de nuevo.",
        'warningNoNumber': "Olvidaste introducir tu número móvil.",
        'warningCodeLength': "Debes introducir el código de 4 dígitos que se envió a tu número telefónico.",
        'warningCodeInvalid': "Ese código de verificación no es válido.",
        'messageWelcomeDashboard': "Bienvenido a tu Panel de Control",
        'enterCode': "Introduce el código de confirmación de 4 dígitos",
        'enterCodeExtra': "Fue enviado en un mensaje de texto a",
        'emailLogin': "Tu código de inicio para AnyPhone es",
        'dashboardWelcome': "Bienvenido a tu Panel de Control",
        'dashboardNumber': "Tu número",
        'dashboardName': "Tu nombre",
        'dashboardNameHint': "Tony Stark",
        'dashboardSetting1': "Los Vengadores",
        'dashboardSetting2': "Liga de la Justicia",
        'dashboardSetting3': "Protocolo Omega",
        'dashboardUpdate': "Modificar",
        'dashboardFinished': "¿Terminaste?",
        'dashboardLogout': "Cerrar Sesión",
        'alertOK': "OK",
    }
};


module.exports = string;
