var string = {
    'en': {
        'title': "AnyPhone",
        'numberDefault': "555-333-6726",
        'enterPhone': "Please enter your phone number to log in.",
        'enterPhoneExtra': "This example is limited to 10-digit US number.",
        'buttonSubmit': "Continue",
        'buttonVerify': "Verify",
        'warningPhone': "You must enter a 10-digit US phone number including area code.",
        'warningTwilio': "Something went wrong. Please check your Twilio configuration.",
        'warningGeneral': "Something went wrong. Please try again.",
        'warningNoNumber': "You forgot to enter your mobile number.",
        'warningCodeLength': "You must enter a 4 digit code texted to your phone number.",
        'warningCodeInvalid': "That verification code is not valid.",
        'messageWelcomeDashboard': "Welcome to your Dashboard",
        'enterCode': "Enter the 4-digit confirmation code",
        'enterCodeExtra': "It was sent in an SMS message to",
        'emailLogin': "Your login code for AnyPhone is",
        'dashboardWelcome': "Welcome to your Dashboard",
        'dashboardNumber': "Your Number",
        'dashboardName': "Your Name",
        'dashboardNameHint': "Nick Fury",
        'dashboardSetting1': "Orbital Tracking Grid",
        'dashboardSetting2': "Iron Legion",
        'dashboardSetting3': "Theta Protocol",
        'dashboardUpdate': "Update",
        'dashboardFinished': "Are you finished?",
        'dashboardLogout': "Logout",
        'alertOK': "OK",
    },
    'ja': {
        'title': "AnyPhone - エニーフォン",
        'numberDefault': "090-1234-5678",
        'enterPhone': "ログインするには電話番号を入力してください。",
        'enterPhoneExtra': "この例は、米国の11桁と日本の10桁の番号に限定されています。",
        'buttonSubmit': "続ける",
        'buttonVerify': "確認",
        'warningPhone': "市外局番をまたは日本の11桁の電話番号を入力してください。",
        'warningTwilio': "問題が発生しました。お客様のTwilio設定を確認してください。",
        'warningGeneral': "問題が発生しました。もう一度試してください。",
        'warningNoNumber': "携帯番号の入力をお忘れです。",
        'warningCodeLength': "お客様の電話番号へ送信されたテキストメッセージに記載の4桁のコードを入力してください。",
        'warningCodeInvalid': "その確認コードは正しくありません。",
        'messageWelcomeDashboard': "ダッシュボードへようこそ。",
        'enterCode': "4桁の確認コードを入力してください",
        'enterCodeExtra': "SMSメッセージにてこちらへ送信されました",
        'emailLogin': "あなたのエニーフォンのログインコードは",
        'dashboardWelcome': "ダシボールド　へ　ようこそ",
        'dashboardNumber': "あなたのばんごう",
        'dashboardName': "あなたのなまえ",
        'dashboardNameHint': "ニーク　フューリー",
        'dashboardSetting1': "オービトル　ツラキング グリド",
        'dashboardSetting2': "アイヨン　リジョン",
        'dashboardSetting3': "シェタ　プロトコル",
        'dashboardUpdate': "アップデート",
        'dashboardFinished': "終わりましたか？",
        'dashboardLogout': "ログアウト",
        'alertOK': "はい",
    },
    'es': {
        'title': "AnyPhone",
        'numberDefault': "090-1234-5678",
        'enterPhone': "Introduce tu número",
        'enterPhoneExtra': "Este ejemplo está limitado a un número de 10-digitos (US)",
        'buttonSubmit': "Continuar",
        'buttonVerify': "Verificar",
        'warningPhone': "Debes introducir un número de 10 dígitos incluyendo su código de área (US)",
        'warningTwilio': "Algo salió mal. Por favor verifica tú configuración de Twilio.",
        'warningGeneral': "Algo salió mal. Por favor intenta de nuevo.",
        'warningNoNumber': "Olvidaste introducir tu número móvil.",
        'warningCodeLength': "Debes introducir el código de 4 dígitos que se envió a tu número telefónico.",
        'warningCodeInvalid': "Ese código de verificación no es válido.",
        'messageWelcomeDashboard': "Bienvenido a tu Panel de Control",
        'enterCode': "Introduce el código de confirmación de 4 dígitos",
        'enterCodeExtra': "Fue enviado en un mensaje de texto a",
        'emailLogin': "Tu código de inicio para AnyPhone es",
        'dashboardWelcome': "Bienvenido a tu Panel de Control",
        'dashboardNumber': "Tu número",
        'dashboardName': "Tu nombre",
        'dashboardNameHint': "Tony Stark",
        'dashboardSetting1': "Los Vengadores",
        'dashboardSetting2': "Liga de la Justicia",
        'dashboardSetting3': "Protocolo Omega",
        'dashboardUpdate': "Modificar",
        'dashboardFinished': "¿Terminaste?",
        'dashboardLogout': "Cerrar Sesión",
        'alertOK': "OK",
    },
    'kr': {
        'title': "AnyPhone - 애니폰",
        'numberDefault': "010-9999-9999",
        'enterPhone': "로그인하려면 휴대폰 전화번호를 입력하십시오.",
        'enterPhoneExtra': "이 예제에서 대한민국은 11자리 숫자로 제한되어 있습니다.",
        'buttonSubmit': "계속",
        'buttonVerify': "확인",
        'warningPhone': "11자리 휴대폰 전화번호를 입력하십시오.",
        'warningTwilio': "문제가 발생했습니다. 귀하의 Twilio 설정을 확인하십시오.",
        'warningGeneral': "문제가 발생했습니다. 다시 시도하십시오.",
        'warningNoNumber': "휴대폰 번호를 입력하지 않았습니다.",
        'warningCodeLength': "귀하의 전화번호로 전송 된 문자 메시지에 기재된 4자리 코드를 입력하십시오.",
        'warningCodeInvalid': "확인 코드가 올바르지 않습니다.",
        'messageWelcomeDashboard': "대시 보드에 오신 것을 환영합니다.",
        'enterCode': "4자리 인증 코드를 입력 해주세요",
        'enterCodeExtra': "SMS 메시지에서 이쪽으로 전송되었습니다",
        'emailLogin': "당신의 애니폰의 로그인 코드가",
        'dashboardWelcome': "대시 보드에 오신 것을 환영합니다",
        'dashboardNumber': "전화번호",
        'dashboardName': "이름",
        'dashboardNameHint': "홍길동",
        'dashboardSetting1': "강남 스타일",
        'dashboardSetting2': "싸이",
        'dashboardSetting3': "소녀시대",
        'dashboardUpdate': "업데이트",
        'dashboardFinished': "끝났습니까?",
        'dashboardLogout': "로그 아웃",
        'alertOK': "예",
    },
    'pt-BR': {
        'title': "AnyPhone - QualquerTelefone",
        'numberDefault': "11-99999-9999",
        'enterPhone': "Por favor insira seu telefone para entrar.",
        'enterPhoneExtra': "Esse exemplo é limitado a números brasileiros de 10 ou 11 dígitos.",
        'buttonSubmit': "Continuar",
        'buttonVerify': "Verificar",
        'warningPhone': "Você precisa inserir um número brasileiro de 10 ou 11 dígitos, incluindo DDD.",
        'warningTwilio': "Aconteceu um problema. Por favor verifique sua configuração do Twilio.",
        'warningGeneral': "Aconteceu um problema. Por favor tente novamente.",
        'warningNoNumber': "Você esqueceu de inserir seu número de telefone.",
        'warningCodeLength': "Você precisa inserir um código de 4 dígitos enviado via mensagem de texto para o seu número de telefone.",
        'warningCodeInvalid': "Esse código de verificação não é válido.",
        'messageWelcomeDashboard': "Bem-vindo a sua Área de Usuário",
        'enterCode': "Insira o código de confirmação de 4 dígitos",
        'enterCodeExtra': "Ele foi enviado em uma mensagem de texto para",
        'emailLogin': "Seu código de login para AnyPhone é",
        'dashboardWelcome': "Bem-vindo a sua Área de Usuário",
        'dashboardNumber': "Seu Telefone",
        'dashboardName': "Seu Nome",
        'dashboardNameHint': "Roberto Nascimento",
        'dashboardSetting1': "BOPE",
        'dashboardSetting2': "Equipe Alfa",
        'dashboardSetting3': "Tenente-Coronel",
        'dashboardUpdate': "Atualizar",
        'dashboardFinished': "Você terminou?",
        'dashboardLogout': "Sair",
        'alertOK': "OK",
    }
};


module.exports = string;
