-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2lM0UOLB3ajLtbBi
Amrowb7K5/ncsw/SJ1ZFiFcafSmgCgYIKoZIzj0DAQehRANCAAQl0g/GsoigBQax
eHt+sX4IlzdKWLsI2ZOkWWd4cG0GvLjKNixWOnUwWMeLZuv/CR7iHYwGIfaa1Nme
vg25FvYg
-----END PRIVATE KEY-----